/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterCommand"];
                    "text/json": components["schemas"]["RegisterCommand"];
                    "application/*+json": components["schemas"]["RegisterCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginCommand"];
                    "text/json": components["schemas"]["LoginCommand"];
                    "application/*+json": components["schemas"]["LoginCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FriendsResult"];
                        "application/json": components["schemas"]["FriendsResult"];
                        "text/json": components["schemas"]["FriendsResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendFriendRequestRequest"];
                    "text/json": components["schemas"]["SendFriendRequestRequest"];
                    "application/*+json": components["schemas"]["SendFriendRequestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SendRequestResult"];
                        "application/json": components["schemas"]["SendRequestResult"];
                        "text/json": components["schemas"]["SendRequestResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends/{requesterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requesterId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RespondToRequestRequest"];
                    "text/json": components["schemas"]["RespondToRequestRequest"];
                    "application/*+json": components["schemas"]["RespondToRequestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/friends/{friendId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    friendId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcceptInvitationRequest"];
                    "text/json": components["schemas"]["AcceptInvitationRequest"];
                    "application/*+json": components["schemas"]["AcceptInvitationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{listId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                    search?: string;
                    statusIds?: (number | string)[];
                    sortBy?: components["schemas"]["ItemSortBy"];
                    ascending?: boolean;
                };
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfTodoItemResponse"];
                        "application/json": components["schemas"]["PagedResultOfTodoItemResponse"];
                        "text/json": components["schemas"]["PagedResultOfTodoItemResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateItemRequest"];
                    "text/json": components["schemas"]["CreateItemRequest"];
                    "application/*+json": components["schemas"]["CreateItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoItemResponse"];
                        "application/json": components["schemas"]["TodoItemResponse"];
                        "text/json": components["schemas"]["TodoItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{listId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoItemResponse"];
                        "application/json": components["schemas"]["TodoItemResponse"];
                        "text/json": components["schemas"]["TodoItemResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateItemRequest"];
                    "text/json": components["schemas"]["UpdateItemRequest"];
                    "application/*+json": components["schemas"]["UpdateItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoItemResponse"];
                        "application/json": components["schemas"]["TodoItemResponse"];
                        "text/json": components["schemas"]["TodoItemResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoListResponse"][];
                        "application/json": components["schemas"]["TodoListResponse"][];
                        "text/json": components["schemas"]["TodoListResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateListRequest"];
                    "text/json": components["schemas"]["CreateListRequest"];
                    "application/*+json": components["schemas"]["CreateListRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoListResponse"];
                        "application/json": components["schemas"]["TodoListResponse"];
                        "text/json": components["schemas"]["TodoListResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{listId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoListResponse"];
                        "application/json": components["schemas"]["TodoListResponse"];
                        "text/json": components["schemas"]["TodoListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateListRequest"];
                    "text/json": components["schemas"]["UpdateListRequest"];
                    "application/*+json": components["schemas"]["UpdateListRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoListResponse"];
                        "application/json": components["schemas"]["TodoListResponse"];
                        "text/json": components["schemas"]["TodoListResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/lists/{listId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoListResponse"];
                        "application/json": components["schemas"]["TodoListResponse"];
                        "text/json": components["schemas"]["TodoListResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{listId}/addable-friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AddableFriendResponse"][];
                        "application/json": components["schemas"]["AddableFriendResponse"][];
                        "text/json": components["schemas"]["AddableFriendResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{listId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TagDto"][];
                        "application/json": components["schemas"]["TagDto"][];
                        "text/json": components["schemas"]["TagDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{listId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ActivityLogResponse"][];
                        "application/json": components["schemas"]["ActivityLogResponse"][];
                        "text/json": components["schemas"]["ActivityLogResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{listId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MemberResponse"][];
                        "application/json": components["schemas"]["MemberResponse"][];
                        "text/json": components["schemas"]["MemberResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddMemberRequest"];
                    "text/json": components["schemas"]["AddMemberRequest"];
                    "application/*+json": components["schemas"]["AddMemberRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MemberResponse"];
                        "application/json": components["schemas"]["MemberResponse"];
                        "text/json": components["schemas"]["MemberResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{listId}/members/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                    profileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MemberResponse"];
                        "application/json": components["schemas"]["MemberResponse"];
                        "text/json": components["schemas"]["MemberResponse"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                    profileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                    profileId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateMemberRoleRequest"];
                    "text/json": components["schemas"]["UpdateMemberRoleRequest"];
                    "application/*+json": components["schemas"]["UpdateMemberRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MemberResponse"];
                        "application/json": components["schemas"]["MemberResponse"];
                        "text/json": components["schemas"]["MemberResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfileResponse"];
                        "application/json": components["schemas"]["ProfileResponse"];
                        "text/json": components["schemas"]["ProfileResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                    "text/json": components["schemas"]["UpdateProfileRequest"];
                    "application/*+json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfileResponse"];
                        "application/json": components["schemas"]["ProfileResponse"];
                        "text/json": components["schemas"]["ProfileResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/profile/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfileResponse"];
                        "application/json": components["schemas"]["ProfileResponse"];
                        "text/json": components["schemas"]["ProfileResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                    "text/json": components["schemas"]["ChangePasswordRequest"];
                    "application/*+json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TagDto"][];
                        "application/json": components["schemas"]["TagDto"][];
                        "text/json": components["schemas"]["TagDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTagRequest"];
                    "text/json": components["schemas"]["CreateTagRequest"];
                    "application/*+json": components["schemas"]["CreateTagRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TagDto"];
                        "application/json": components["schemas"]["TagDto"];
                        "text/json": components["schemas"]["TagDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{listId}/items/{itemId}/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                    itemId: string;
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: string;
                    itemId: string;
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInvitationRequest: {
            token: string;
        };
        ActivityLogResponse: {
            /** Format: uuid */
            id: string;
            actionType: string;
            actorName: string;
            detail: null | string;
            /** Format: date-time */
            timestamp: string;
        };
        AddableFriendResponse: {
            /** Format: uuid */
            profileId: string;
            displayName: string;
            email: string;
            avatarUrl: null | string;
        };
        AddMemberRequest: {
            email: string;
            role: components["schemas"]["MemberRole"];
        };
        AssigneeDto: {
            /** Format: uuid */
            id: string;
            displayName: string;
        };
        AuthResponse: {
            token: string;
            /** Format: uuid */
            profileId: string;
            displayName: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CreateItemRequest: {
            content: string;
            notes: null | string;
            dueDate: null | string;
            /** Format: uuid */
            assignedToId: null | string;
        };
        CreateListRequest: {
            title: string;
        };
        CreateTagRequest: {
            name: string;
            color: string;
        };
        FriendResponse: {
            /** Format: uuid */
            profileId: string;
            displayName: string;
            email: string;
            avatarUrl: null | string;
        };
        FriendsResult: {
            friends: components["schemas"]["FriendResponse"][];
            pendingReceived: components["schemas"]["ReceivedRequestResponse"][];
            pendingSent: components["schemas"]["SentRequestResponse"][];
        };
        /** Format: binary */
        IFormFile: string;
        ItemSortBy: number;
        LoginCommand: {
            email: string;
            password: string;
        };
        MemberResponse: {
            /** Format: uuid */
            profileId: string;
            displayName: string;
            avatarUrl: null | string;
            role: components["schemas"]["MemberRole"];
            /** Format: date-time */
            joinedAt: string;
        };
        MemberRole: number;
        PagedResultOfTodoItemResponse: {
            items: components["schemas"]["TodoItemResponse"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasNextPage?: boolean;
            hasPreviousPage?: boolean;
        };
        ProfileResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            displayName: string;
            phoneNumber: null | string;
            avatarUrl: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        ReceivedRequestResponse: {
            /** Format: uuid */
            requesterId: string;
            displayName: string;
            email: string;
            avatarUrl: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        RegisterCommand: {
            email: string;
            password: string;
            displayName: string;
        };
        RespondToRequestRequest: {
            accept: boolean;
        };
        SendFriendRequestRequest: {
            email: string;
        };
        SendRequestResult: {
            invitationSent: boolean;
        };
        SentRequestResponse: {
            /** Format: uuid */
            addresseeId: string;
            displayName: string;
            email: string;
            avatarUrl: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        StatusDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
        };
        TagDto: {
            /** Format: uuid */
            id: string;
            name: string;
            color: string;
        };
        TodoItemResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            listId: string;
            content: string;
            status: components["schemas"]["StatusDto"];
            notes: null | string;
            dueDate: null | string;
            assignedTo: null | components["schemas"]["AssigneeDto"];
            tags: components["schemas"]["TagDto"][];
            isStarred: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TodoListResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            role: components["schemas"]["MemberRole"];
            ownerName: string;
            contributorNames: string[];
            /** Format: int32 */
            memberCount: number | string;
            /** Format: int32 */
            notStartedCount: number | string;
            /** Format: int32 */
            partialCount: number | string;
            /** Format: int32 */
            completeCount: number | string;
            /** Format: int32 */
            abandonedCount: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            closedAt: null | string;
            tags: components["schemas"]["TagDto"][];
        };
        UpdateItemRequest: {
            content: null | string;
            /** Format: int32 */
            statusId: null | number | string;
            notes: null | string;
            dueDate: null | string;
            /** Format: uuid */
            assignedToId: null | string;
            /** @default false */
            clearDueDate: boolean;
            /** @default false */
            clearAssignee: boolean;
            isStarred?: null | boolean;
        };
        UpdateListRequest: {
            title: string;
        };
        UpdateMemberRoleRequest: {
            role: components["schemas"]["MemberRole"];
        };
        UpdateProfileRequest: {
            displayName: string;
            phoneNumber: null | string;
            avatarUrl: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
